export type TechDetails = Record<
  string,
  { icon: string; color: string; name: string; darkmodecolor?: string }
>;

export const TECH_STACK_DETAILS: TechDetails = {
  'react.js': {
    icon: 'logos:react',
    color: 'rgb(97 218 251)',
    name: 'React.js',
    darkmodecolor: 'rgb(97 218 251)',
  },
  react: {
    icon: 'logos:react',
    color: 'rgb(97 218 251)',
    name: 'React.js',
    darkmodecolor: 'rgb(97 218 251)',
  },
  'next.js': {
    icon: 'material-icon-theme:next',
    color: 'rgb(15 23 42)',
    darkmodecolor: 'rgb(248 250 252)',
    name: 'Next.js',
  },
  redux: {
    icon: 'logos:redux',
    color: 'rgb(118 74 188)',
    name: 'Redux',
    darkmodecolor: 'rgb(167 139 250)',
  },
  typescript: {
    icon: 'logos:typescript-icon',
    color: 'rgb(49 120 198)',
    name: 'TypeScript',
    darkmodecolor: 'rgb(96 165 250)',
  },
  javascript: {
    icon: 'logos:javascript',
    color: 'rgb(247 223 30)',
    name: 'JavaScript',
    darkmodecolor: 'rgb(253 224 71)',
  },
  'javascript (es6+)': {
    icon: 'logos:javascript',
    color: 'rgb(247 223 30)',
    name: 'JavaScript (ES6+)',
    darkmodecolor: 'rgb(253 224 71)',
  },
  html: {
    icon: 'logos:html-5',
    color: 'rgb(227 79 38)',
    name: 'HTML',
    darkmodecolor: 'rgb(251 146 60)',
  },
  html5: {
    icon: 'logos:html-5',
    color: 'rgb(227 79 38)',
    name: 'HTML5',
    darkmodecolor: 'rgb(251 146 60)',
  },
  css: {
    icon: 'logos:css-3',
    color: 'rgb(21 114 182)',
    name: 'CSS',
    darkmodecolor: 'rgb(56 189 248)',
  },
  css3: {
    icon: 'logos:css-3',
    color: 'rgb(21 114 182)',
    name: 'CSS3',
    darkmodecolor: 'rgb(56 189 248)',
  },
  'tailwind css': {
    icon: 'logos:tailwindcss-icon',
    color: 'rgb(6 182 212)',
    name: 'Tailwind CSS',
    darkmodecolor: 'rgb(34 211 238)',
  },
  'shadcn/ui': {
    icon: 'simple-icons:shadcnui',
    color: 'rgb(15 23 42)',
    darkmodecolor: 'rgb(248 250 252)',
    name: 'Shadcn/UI',
  },
  'material-ui': {
    icon: 'logos:material-ui',
    color: 'rgb(0 127 255)',
    name: 'Material-UI',
    darkmodecolor: 'rgb(96 165 250)',
  },
  'chakra ui': {
    icon: 'devicon:chakraui',
    color: 'rgb(49 151 149)',
    name: 'Chakra UI',
    darkmodecolor: 'rgb(94 234 212)',
  },
  'radix ui': {
    icon: 'simple-icons:radixui',
    color: 'rgb(15 23 42)',
    darkmodecolor: 'rgb(248 250 252)',
    name: 'Radix UI',
  },
  scss: {
    icon: 'vscode-icons:file-type-scss',
    color: 'rgb(205 103 153)',
    name: 'SCSS',
    darkmodecolor: 'rgb(244 114 182)',
  },

  'node.js': {
    icon: 'logos:nodejs-icon',
    color: 'rgb(51 153 51)',
    name: 'Node.js',
    darkmodecolor: 'rgb(134 239 172)',
  },
  'bun.js': {
    icon: 'logos:bun',
    color: 'rgb(251 240 223)',
    name: 'Bun.js',
    darkmodecolor: 'rgb(254 243 199)',
  },
  'hono.js': {
    icon: 'logos:hono',
    color: 'rgb(227 96 2)',
    name: 'Hono.js',
    darkmodecolor: 'rgb(251 146 60)',
  },
  'express.js': {
    icon: 'simple-icons:express',
    color: 'rgb(51 51 51)',
    darkmodecolor: 'rgb(226 232 240)',
    name: 'Express.js',
  },
  'restful apis': {
    icon: 'mdi:api',
    color: 'rgb(100 116 139)',
    name: 'RESTful APIs',
    darkmodecolor: 'rgb(148 163 184)',
  },
  graphql: {
    icon: 'logos:graphql',
    color: 'rgb(225 0 152)',
    name: 'GraphQL',
    darkmodecolor: 'rgb(244 114 182)',
  },
  microservices: {
    icon: 'carbon:microservices-1',
    color: 'rgb(59 130 246)',
    name: 'Microservices',
    darkmodecolor: 'rgb(96 165 250)',
  },
  websockets: {
    icon: 'logos:socket-io',
    color: 'rgb(30 41 59)',
    darkmodecolor: 'rgb(226 232 240)',
    name: 'WebSockets',
  },
  'websocket api': {
    icon: 'logos:socket-io',
    color: 'rgb(30 41 59)',
    darkmodecolor: 'rgb(226 232 240)',
    name: 'WebSocket API',
  },
  serverless: {
    icon: 'logos:aws-lambda',
    color: 'rgb(255 153 0)',
    name: 'Serverless',
    darkmodecolor: 'rgb(251 191 36)',
  },

  postgresql: {
    icon: 'logos:postgresql',
    color: 'rgb(65 105 225)',
    name: 'PostgreSQL',
    darkmodecolor: 'rgb(96 165 250)',
  },
  mongodb: {
    icon: 'logos:mongodb-icon',
    color: 'rgb(71 162 72)',
    name: 'MongoDB',
    darkmodecolor: 'rgb(134 239 172)',
  },
  mysql: {
    icon: 'logos:mysql',
    color: 'rgb(68 121 161)',
    name: 'MySQL',
    darkmodecolor: 'rgb(96 165 250)',
  },
  convex: {
    icon: 'solar:database-bold',
    color: 'rgb(71 85 105)',
    name: 'Convex',
    darkmodecolor: 'rgb(226 232 240)',
  },
  redis: {
    icon: 'logos:redis',
    color: 'rgb(220 56 45)',
    name: 'Redis',
    darkmodecolor: 'rgb(248 113 113)',
  },
  firebase: {
    icon: 'vscode-icons:file-type-firebase',
    color: 'rgb(255 202 40)',
    name: 'Firebase',
    darkmodecolor: 'rgb(251 191 36)',
  },
  'drizzle orm': {
    icon: 'simple-icons:drizzle',
    color: 'rgb(132 204 22)',
    name: 'Drizzle ORM',
    darkmodecolor: 'rgb(163 230 53)',
  },
  prisma: {
    icon: 'simple-icons:prisma',
    color: 'rgb(45 55 72)',
    darkmodecolor: 'rgb(226 232 240)',
    name: 'Prisma',
  },
  neondb: {
    icon: 'logos:neon-icon',
    name: 'NeonDB',
    color: '#00E6A1',
  },

  cloudflare: {
    icon: 'logos:cloudflare-icon',
    color: 'rgb(243 128 32)',
    name: 'Cloudflare',
    darkmodecolor: 'rgb(251 146 60)',
  },
  'cloudflare workers': {
    icon: 'logos:cloudflare-workers-icon',
    color: '#F38020',
    name: 'Cloudflare Workers',
  },
  'cloudflare pages': {
    icon: 'devicon:cloudflare',
    color: '#F38020',
    name: 'Cloudflare Pages',
  },
  vercel: {
    icon: 'ion:logo-vercel',
    color: 'rgb(15 23 42)',
    darkmodecolor: 'rgb(248 250 252)',
    name: 'Vercel',
  },
  aws: {
    icon: 'logos:aws',
    color: 'rgb(255 153 0)',
    name: 'AWS',
    darkmodecolor: 'rgb(251 191 36)',
  },
  netlify: {
    icon: 'logos:netlify-icon',
    color: 'rgb(0 199 183)',
    name: 'Netlify',
    darkmodecolor: 'rgb(94 234 212)',
  },
  'ci/cd (github actions)': {
    icon: 'logos:github-actions',
    color: 'rgb(32 136 255)',
    name: 'CI/CD',
    darkmodecolor: 'rgb(96 165 250)',
  },
  docker: {
    icon: 'logos:docker-icon',
    color: 'rgb(36 150 237)',
    name: 'Docker',
    darkmodecolor: 'rgb(56 189 248)',
  },
  git: {
    icon: 'logos:git-icon',
    color: 'rgb(240 80 50)',
    name: 'Git',
    darkmodecolor: 'rgb(248 113 113)',
  },
  shell: { icon: 'gg:terminal', color: '#75B35B', name: 'Shell' },
  markdown: {
    icon: 'material-icon-theme:mdx',
    color: '#000000',
    darkmodecolor: '#FFFFFF',
    name: 'Markdown',
  },
  ai: { icon: 'ix:ai', color: '#8A2BE2', name: 'AI' },
  'gemini ai': { icon: 'simple-icons:googlebard', color: '#8E44AD', name: 'Gemini AI' },

  'generative ai': {
    icon: 'carbon:machine-learning-model',
    color: 'rgb(124 58 237)',
    name: 'Generative AI',
    darkmodecolor: 'rgb(167 139 250)',
  },
  llms: {
    icon: 'fluent:brain-circuit-24-regular',
    color: 'rgb(99 102 241)',
    name: 'LLMs',
    darkmodecolor: 'rgb(129 140 248)',
  },
  'api security': {
    icon: 'material-symbols:security',
    color: 'rgb(185 28 28)',
    name: 'API Security',
    darkmodecolor: 'rgb(248 113 113)',
  },
  'performance opt.': {
    icon: 'fluent-mdl2:speed-high',
    color: 'rgb(34 197 94)',
    name: 'Performance Opt.',
    darkmodecolor: 'rgb(134 239 172)',
  },
  scalability: {
    icon: 'mdi:chart-gantt',
    color: 'rgb(202 138 4)',
    name: 'Scalability',
    darkmodecolor: 'rgb(250 204 21)',
  },
  'fal.ai api': { icon: 'logos:fal', color: '#0000FF', name: 'Fal.ai API' },
  'fal.ai': { icon: 'logos:fal', color: '#0000FF', name: 'Fal.ai' },

  'vs code': {
    icon: 'logos:visual-studio-code',
    color: 'rgb(0 122 204)',
    name: 'VS Code',
    darkmodecolor: 'rgb(96 165 250)',
  },
  postman: {
    icon: 'logos:postman-icon',
    color: 'rgb(255 108 55)',
    name: 'Postman',
    darkmodecolor: 'rgb(251 146 60)',
  },
  'swagger/openapi': {
    icon: 'logos:swagger',
    color: 'rgb(133 234 45)',
    name: 'Swagger/OpenAPI',
    darkmodecolor: 'rgb(163 230 53)',
  },
  figma: {
    icon: 'logos:figma',
    color: 'rgb(242 78 30)',
    name: 'Figma',
    darkmodecolor: 'rgb(251 146 60)',
  },
  jira: {
    icon: 'logos:jira',
    color: 'rgb(0 82 204)',
    name: 'Jira',
    darkmodecolor: 'rgb(96 165 250)',
  },
  'agile/scrum': {
    icon: 'mdi:account-group-outline',
    color: 'rgb(14 116 144)',
    name: 'Agile/Scrum',
  },
  tdd: { icon: 'mdi:test-tube', color: '#A040A0', name: 'TDD' },
  vite: { icon: 'logos:vitejs', color: '#646CFF', name: 'Vite' },
  'data scraping': { icon: 'carbon:data-share', color: '#48a9a6', name: 'Data Scraping' },
  recharts: { icon: 'fluent-emoji-high-contrast:bar-chart', color: '#8884d8', name: 'Recharts' },
  'chart.js': { icon: 'carbon:chart-line', color: '#FF6384', name: 'Chart.js' },
  jwt: { icon: 'logos:jwt-icon', color: '#000000', darkmodecolor: '#FFFFFF', name: 'JWT' },
  'pdf.js': { icon: 'dashicons:pdf', color: '#FF0000', name: 'PDF.js' },
  webgl: { icon: 'logos:webgl', color: '#990000', name: 'WebGL' },
  mongoose: { icon: 'devicon:mongoose', color: '#880000', name: 'Mongoose' },
  mdx: { icon: 'material-icon-theme:mdx', color: '#000000', darkmodecolor: '#FFFFFF', name: 'MDX' },
  'react native': { icon: 'tabler:brand-react-native', color: '#61DAFB', name: 'React Native' },
  'mobile development': {
    icon: 'eva:smartphone-fill',
    color: '#A0A0A0',
    name: 'Mobile Development',
  },
  expo: { icon: 'simple-icons:expo', color: '#000020', darkmodecolor: '#FFFFFF', name: 'Expo' },
  't3 stack': { icon: 'simple-icons:t3', color: '#2596be', name: 'T3 Stack' },
  trpc: { icon: 'logos:trpc', color: '#398CCB', name: 'tRPC' },
  'nextauth.js': {
    icon: 'simple-icons:nextauth',
    color: '#1F2937',
    darkmodecolor: '#FFFFFF',
    name: 'NextAuth.js',
  },
  'stable diffusion api': {
    icon: 'icon-park-outline:api',
    color: '#000000',
    darkmodecolor: '#FFFFFF',
    name: 'Stable Diffusion API',
  },
  python: { icon: 'logos:python', color: '#3776AB', name: 'Python' },
  'jupyter notebook': { icon: 'logos:jupyter', color: '#F37626', name: 'Jupyter Notebook' },
  'openai api': { icon: 'ri:openai-fill', color: '#412991', name: 'OpenAI API' },
  'fetch api': { icon: 'material-symbols:api-outline', color: '#007ACC', name: 'Fetch API' },
  'coingecko api': { icon: 'simple-icons:coingecko', color: '#8CC63F', name: 'CoinGecko API' },
  'plate.js': {
    icon: 'simple-icons:plate',
    color: '#000000',
    darkmodecolor: '#FFFFFF',
    name: 'Plate.js',
  },
  uploadthing: { icon: 'simple-icons:uploadthing', color: '#7C3AED', name: 'UploadThing' },
  'vercel ai sdk': {
    icon: 'simple-icons:vercel',
    color: '#000000',
    darkmodecolor: '#FFFFFF',
    name: 'Vercel AI SDK',
  },
  'google gemini': { icon: 'simple-icons:googlegemini', color: '#4285F4', name: 'Google Gemini' },
  'three.js': {
    icon: 'skill-icons:threejs-light',
    color: '#000000',
    darkmodecolor: '#FFFFFF',
    name: 'Three.js',
  },
  'sails.js': {
    icon: 'logos:sails',
    color: '#000000',
    darkmodecolor: '#FFFFFF',
    name: 'Sails.js',
  },
  'strapi v4': {
    icon: 'logos:strapi-icon',
    color: '#000000',
    darkmodecolor: '#FFFFFF',
    name: 'Strapi.js',
  },
  'aws sqs': {
    icon: 'logos:aws-sqs',
    color: '#000000',
    darkmodecolor: '#FFFFFF',
    name: 'AWS SQS',
  },
  sql: {
    icon: 'logos:mysql',
    color: '#000000',
    darkmodecolor: '#FFFFFF',
    name: 'SQL',
  },
  'socket.io': {
    icon: 'logos:socket-io',
    color: '#000000',
    darkmodecolor: '#FFFFFF',
    name: 'Socket.io',
  },
  'styled components': {
    icon: 'devicon:styledcomponents',
    color: '#000000',
    darkmodecolor: '#FFFFFF',
    name: 'Styled Components',
  },
  webpack: {
    icon: 'devicon:webpack',
    color: '#000000',
    darkmodecolor: '#FFFFFF',
    name: 'Webpack',
  },
  'Radix UI': {
    icon: 'simple-icons:radixui',
    color: '#000000',
    darkmodecolor: '#FFFFFF',
    name: 'Radix UI',
  },
  ffmpeg: {
    icon: 'logos:ffmpeg-icon',
    color: '#000000',
    darkmodecolor: '#FFFFFF',
    name: 'FFmpeg',
  },
  streaming: {
    icon: 'fluent-mdl2:streaming',
    color: '#000000',
    darkmodecolor: '#FFFFFF',
    name: 'Streaming',
  },
  stripe: {
    icon: 'logos:stripe',
    color: '#000000',
    darkmodecolor: '#FFFFFF',
    name: 'Stripe',
  },
  supabase: {
    icon: 'logos:supabase',
    color: '#000000',
    darkmodecolor: '#FFFFFF',
    name: 'Supabase',
  },
};
