export type TechDetails = Record<
  string,
  { icon: string; color: string; name: string; darkmodecolor?: string }
>;

export const TECH_STACK_DETAILS: TechDetails = {
  'react.js': { icon: 'logos:react', color: '#61DAFB', name: 'React.js' },
  react: { icon: 'logos:react', color: '#61DAFB', name: 'React.js' },
  'next.js': {
    icon: 'material-icon-theme:next',
    color: '#000000',
    darkmodecolor: '#FFFFFF',
    name: 'Next.js',
  },
  redux: { icon: 'logos:redux', color: '#764ABC', name: 'Redux' },
  typescript: {
    icon: 'logos:typescript-icon',
    color: '#3178C6',
    name: 'TypeScript',
  },
  javascript: {
    icon: 'logos:javascript',
    color: '#F7DF1E',
    name: 'JavaScript',
  },
  'javascript (es6+)': {
    icon: 'logos:javascript',
    color: '#F7DF1E',
    name: 'JavaScript (ES6+)',
  },
  html: { icon: 'logos:html-5', color: '#E34F26', name: 'HTML' },
  html5: { icon: 'logos:html-5', color: '#E34F26', name: 'HTML5' },
  css: { icon: 'logos:css-3', color: '#1572B6', name: 'CSS' },
  css3: { icon: 'logos:css-3', color: '#1572B6', name: 'CSS3' },
  'tailwind css': {
    icon: 'logos:tailwindcss-icon',
    color: '#06B6D4',
    name: 'Tailwind CSS',
  },
  'shadcn/ui': {
    icon: 'simple-icons:shadcnui',
    color: '#000000',
    darkmodecolor: '#FFFFFF',
    name: 'Shadcn/UI',
  },
  'material-ui': {
    icon: 'logos:material-ui',
    color: '#007FFF',
    name: 'Material-UI',
  },

  'node.js': { icon: 'logos:nodejs-icon', color: '#339933', name: 'Node.js' },
  'bun.js': { icon: 'logos:bun', color: '#FBF0DF', name: 'Bun.js' },
  'hono.js': { icon: 'logos:hono', color: '#E36002', name: 'Hono.js' },
  'express.js': {
    icon: 'simple-icons:express',
    color: '#000000',
    darkmodecolor: '#FFFFFF',
    name: 'Express.js',
  },
  'restful apis': { icon: 'mdi:api', color: '#85a2b6', name: 'RESTful APIs' },
  graphql: { icon: 'logos:graphql', color: '#E10098', name: 'GraphQL' },
  microservices: {
    icon: 'carbon:microservices-1',
    color: '#3c87c8',
    name: 'Microservices',
  },
  websockets: {
    icon: 'logos:socket-io',
    color: '#010101',
    darkmodecolor: '#FFFFFF',
    name: 'WebSockets',
  },
  'websocket api': {
    icon: 'logos:socket-io',
    color: '#010101',
    darkmodecolor: '#FFFFFF',
    name: 'WebSocket API',
  },
  serverless: {
    icon: 'logos:aws-lambda',
    color: '#FF9900',
    name: 'Serverless',
  },

  postgresql: {
    icon: 'logos:postgresql',
    color: '#4169E1',
    name: 'PostgreSQL',
  },
  mongodb: { icon: 'logos:mongodb-icon', color: '#47A248', name: 'MongoDB' },
  mysql: { icon: 'logos:mysql', color: '#4479A1', name: 'MySQL' },
  redis: { icon: 'logos:redis', color: '#DC382D', name: 'Redis' },
  'drizzle orm': {
    icon: 'simple-icons:drizzle',
    color: '#C5F65F',
    name: 'Drizzle ORM',
  },
  prisma: {
    icon: 'simple-icons:prisma',
    color: '#2D3748',
    darkmodecolor: '#FFFFFF',
    name: 'Prisma',
  },
  neondb: {
    icon: 'logos:neon-icon',
    name: 'NeonDB',
    color: '#00E6A1',
  },

  aws: { icon: 'logos:aws', color: '#FF9900', name: 'AWS' },
  'google cloud (gcp)': {
    icon: 'logos:google-cloud',
    color: '#4285F4',
    name: 'Google Cloud (GCP)',
  },
  cloudflare: {
    icon: 'logos:cloudflare-icon',
    color: '#F38020',
    name: 'Cloudflare',
  },
  'cloudflare workers': {
    icon: 'logos:cloudflare-workers-icon',
    color: '#F38020',
    name: 'Cloudflare Workers',
  },
  'cloudflare pages': {
    icon: 'devicon:cloudflare',
    color: '#F38020',
    name: 'Cloudflare Pages',
  },
  vercel: {
    icon: 'ion:logo-vercel',
    color: '#000000',
    darkmodecolor: '#FFFFFF',
    name: 'Vercel',
  },
  netlify: { icon: 'logos:netlify-icon', color: '#00C7B7', name: 'Netlify' },
  'ci/cd (github actions)': {
    icon: 'logos:github-actions',
    color: '#2088FF',
    name: 'CI/CD',
  },
  docker: { icon: 'logos:docker-icon', color: '#2496ED', name: 'Docker' },
  git: { icon: 'logos:git-icon', color: '#F05032', name: 'Git' },
  shell: { icon: 'gg:terminal', color: '#75B35B', name: 'Shell' },
  markdown: {
    icon: 'material-icon-theme:mdx',
    color: '#000000',
    darkmodecolor: '#FFFFFF',
    name: 'Markdown',
  },

  ai: { icon: 'ix:ai', color: '#8A2BE2', name: 'AI' },
  'gemini ai': { icon: 'simple-icons:googlebard', color: '#8E44AD', name: 'Gemini AI' },
  'generative ai': {
    icon: 'ix:ai',
    color: '#8A2BE2',
    name: 'Generative AI',
  },
  llms: {
    icon: 'fluent:brain-circuit-24-regular',
    color: '#5F9EA0',
    name: 'LLMs',
  },
  'api security': {
    icon: 'material-symbols:security',
    color: '#FF4500',
    name: 'API Security',
  },
  'performance opt.': {
    icon: 'fluent-mdl2:speed-high',
    color: '#32CD32',
    name: 'Performance Opt.',
  },
  scalability: {
    icon: 'mdi:chart-gantt',
    color: '#FFD700',
    name: 'Scalability',
  },
  'fal.ai api': { icon: 'logos:fal', color: '#0000FF', name: 'Fal.ai API' },
  'fal.ai': { icon: 'logos:fal', color: '#0000FF', name: 'Fal.ai' },

  'vs code': {
    icon: 'logos:visual-studio-code',
    color: '#007ACC',
    name: 'VS Code',
  },
  postman: { icon: 'logos:postman-icon', color: '#FF6C37', name: 'Postman' },
  'swagger/openapi': {
    icon: 'logos:swagger',
    color: '#85EA2D',
    name: 'Swagger/OpenAPI',
  },
  figma: { icon: 'logos:figma', color: '#F24E1E', name: 'Figma' },
  jira: { icon: 'logos:jira', color: '#0052CC', name: 'Jira' },
  'agile/scrum': {
    icon: 'mdi:account-group-outline',
    color: '#0098DB',
    name: 'Agile/Scrum',
  },
  tdd: { icon: 'mdi:test-tube', color: '#A040A0', name: 'TDD' },
  vite: { icon: 'logos:vitejs', color: '#646CFF', name: 'Vite' },
  'data scraping': { icon: 'carbon:data-share', color: '#48a9a6', name: 'Data Scraping' },
  recharts: { icon: 'fluent-emoji-high-contrast:bar-chart', color: '#8884d8', name: 'Recharts' },
  'chart.js': { icon: 'carbon:chart-line', color: '#FF6384', name: 'Chart.js' },
  jwt: { icon: 'logos:jwt-icon', color: '#000000', darkmodecolor: '#FFFFFF', name: 'JWT' },
  'pdf.js': { icon: 'dashicons:pdf', color: '#FF0000', name: 'PDF.js' },
  webgl: { icon: 'logos:webgl', color: '#990000', name: 'WebGL' },
  mongoose: { icon: 'devicon:mongoose', color: '#880000', name: 'Mongoose' },
  mdx: { icon: 'material-icon-theme:mdx', color: '#000000', darkmodecolor: '#FFFFFF', name: 'MDX' },
  'react native': { icon: 'tabler:brand-react-native', color: '#61DAFB', name: 'React Native' },
  'mobile development': {
    icon: 'eva:smartphone-fill',
    color: '#A0A0A0',
    name: 'Mobile Development',
  },
  expo: { icon: 'simple-icons:expo', color: '#000020', darkmodecolor: '#FFFFFF', name: 'Expo' },
  't3 stack': { icon: 'simple-icons:t3', color: '#2596be', name: 'T3 Stack' },
  trpc: { icon: 'logos:trpc', color: '#398CCB', name: 'tRPC' },
  'nextauth.js': {
    icon: 'simple-icons:nextauth',
    color: '#1F2937',
    darkmodecolor: '#FFFFFF',
    name: 'NextAuth.js',
  },
  'stable diffusion api': {
    icon: 'icon-park-outline:api',
    color: '#000000',
    darkmodecolor: '#FFFFFF',
    name: 'Stable Diffusion API',
  },
  python: { icon: 'logos:python', color: '#3776AB', name: 'Python' },
  'jupyter notebook': { icon: 'logos:jupyter', color: '#F37626', name: 'Jupyter Notebook' },
  'openai api': { icon: 'ri:openai-fill', color: '#412991', name: 'OpenAI API' },
  'fetch api': { icon: 'material-symbols:api-outline', color: '#007ACC', name: 'Fetch API' },
  'coingecko api': { icon: 'simple-icons:coingecko', color: '#8CC63F', name: 'CoinGecko API' },
  convex: { icon: 'logos:convex', color: '#475569', darkmodecolor: '#E2E8F0', name: 'Convex' },
  'plate.js': {
    icon: 'simple-icons:plate',
    color: '#000000',
    darkmodecolor: '#FFFFFF',
    name: 'Plate.js',
  },
  uploadthing: { icon: 'simple-icons:uploadthing', color: '#7C3AED', name: 'UploadThing' },
  'vercel ai sdk': {
    icon: 'simple-icons:vercel',
    color: '#000000',
    darkmodecolor: '#FFFFFF',
    name: 'Vercel AI SDK',
  },
  'google gemini': { icon: 'simple-icons:googlegemini', color: '#4285F4', name: 'Google Gemini' },
  'three.js': {
    icon: 'skill-icons:threejs-light',
    color: '#000000',
    darkmodecolor: '#FFFFFF',
    name: 'Three.js',
  },
  'sails.js': {
    icon: 'logos:sails',
    color: '#000000',
    darkmodecolor: '#FFFFFF',
    name: 'Sails.js',
  },
  'strapi v4': {
    icon: 'logos:strapi-icon',
    color: '#000000',
    darkmodecolor: '#FFFFFF',
    name: 'Strapi.js',
  },
  'aws sqs': {
    icon: 'logos:aws-sqs',
    color: '#000000',
    darkmodecolor: '#FFFFFF',
    name: 'AWS SQS',
  },
  sql: {
    icon: 'logos:mysql',
    color: '#000000',
    darkmodecolor: '#FFFFFF',
    name: 'SQL',
  },
  'socket.io': {
    icon: 'logos:socket-io',
    color: '#000000',
    darkmodecolor: '#FFFFFF',
    name: 'Socket.io',
  },
  'styled components': {
    icon: 'devicon:styledcomponents',
    color: '#000000',
    darkmodecolor: '#FFFFFF',
    name: 'Styled Components',
  },
  webpack: {
    icon: 'devicon:webpack',
    color: '#000000',
    darkmodecolor: '#FFFFFF',
    name: 'Webpack',
  },
  'Radix UI': {
    icon: 'simple-icons:radixui',
    color: '#000000',
    darkmodecolor: '#FFFFFF',
    name: 'Radix UI',
  },
};
