export interface ThemeColors {
  REGULAR_CHAR_COLOR_SOURCE: string;
  LEADING_CHAR_COLOR_SOURCE: string;
  REGULAR_CHAR_ALPHA: number;
  LEADING_CHAR_ALPHA: number;
}

export interface MatrixRainConfig {
  PREFILL_DURATION_SECONDS: number;
  CHAR_SET: string;
  LEADING_CHAR_SUBSET: string;
  FONT_SIZE_PX: number;
  TEXTURE_RESOLUTION_MULTIPLIER: number;
  COLUMN_BASE_WIDTH_PX_FACTOR: number;
  CHAR_BASE_HEIGHT_PX_FACTOR: number;
  MIN_SPRITE_SCALE: number;
  MAX_SPRITE_SCALE: number;
  LEADING_CHAR_GLOW_OPACITY: number;
  LEADING_CHAR_GLOW_BLUR: number;
  LEADING_CHAR_TAIL_LENGTH: number;
  LEADING_CHAR_TAIL_DIM_FACTOR_START: number;
  LEADING_CHAR_TAIL_DIM_FACTOR_END: number;
  LIGHT_THEME_COLORS: ThemeColors;
  DARK_THEME_COLORS: ThemeColors;
  EFFECTIVE_REGULAR_CHAR_RGBA: string;
  EFFECTIVE_LEADING_CHAR_RGBA: string;
  MOUSE_INTERACTION_RADIUS: number;
  MOUSE_PUSH_STRENGTH_FACTOR: number;
  MOUSE_SPEED_INCREASE_FACTOR: number;
  MOUSE_INTERACTION_MAX_Z_DEPTH: number;
  MOUSE_RIPPLE_STRENGTH_FACTOR: number;
  MOUSE_RIPPLE_FREQUENCY_FACTOR: number;
  INTERACTION_LERP_SPEED: number;
  MOUSE_RIPPLE_LERP_SPEED: number;
  MOUSE_INTERACTION_SCALE_FACTOR: number;
  BASE_Y_VELOCITY_MIN_FACTOR: number;
  BASE_Y_VELOCITY_MAX_FACTOR: number;
  Y_VELOCITY_DELTA_MULTIPLIER: number;
  MIN_SPAWN_INTERVAL_MS: number;
  MAX_SPAWN_INTERVAL_MS: number;
  HORIZONTAL_DRIFT_SPEED_FACTOR: number;
  HORIZONTAL_DRIFT_AMPLITUDE_MIN_FACTOR: number;
  HORIZONTAL_DRIFT_AMPLITUDE_MAX_FACTOR: number;
  HORIZONTAL_DRIFT_Y_POS_FACTOR: number;
  SPRITE_FADE_IN_DISTANCE_CHARS: number;
  SPRITE_FADE_OUT_DISTANCE_CHARS: number;
  MIN_TARGET_OPACITY_REGULAR: number;
  MAX_TARGET_OPACITY_REGULAR: number;
  TARGET_OPACITY_LEADING: number;
  OPACITY_LERP_SPEED: number;
  NON_LEADING_CHAR_CHANGE_CHANCE: number;
  LEADING_CHAR_CHANGE_CHANCE: number;
  RENDERER_PIXEL_RATIO_CAP: number;
  RENDERER_ANTIALIAS: boolean;
  STREAM_MIN_DEPTH_FACTOR: number;
  STREAM_MAX_DEPTH_FACTOR: number;
  CAMERA_FOV: number;
  CAMERA_NEAR_PLANE: number;
  CAMERA_FAR_PLANE: number;
  CAMERA_INITIAL_Z_POS: number;
  MIN_STREAM_Z_DEPTH: number;
  MAX_STREAM_Z_DEPTH: number;
  SPAWN_VOLUME_Y_HALF_HEIGHT: number;
  SPAWN_VOLUME_X_SPREAD_FACTOR: number;
}

const baseConfig: MatrixRainConfig = {
  PREFILL_DURATION_SECONDS: 1.8,
  CHAR_SET: "abcdefklmnopqrxyz0123456789ﾊﾐﾋｰﾚﾛﾝ<>{}%#@:.+=日木国語",
  LEADING_CHAR_SUBSET: "ABCDEFGHIOPQRSTUVWXYZ012語",
  FONT_SIZE_PX: 8,
  TEXTURE_RESOLUTION_MULTIPLIER: 2,
  COLUMN_BASE_WIDTH_PX_FACTOR: 1.2,
  CHAR_BASE_HEIGHT_PX_FACTOR: 2,
  MIN_SPRITE_SCALE: 0.6,
  MAX_SPRITE_SCALE: 1.3,
  LEADING_CHAR_GLOW_OPACITY: 0.12,
  LEADING_CHAR_GLOW_BLUR: 0.9,
  LEADING_CHAR_TAIL_LENGTH: 5,
  LEADING_CHAR_TAIL_DIM_FACTOR_START: 0.7,
  LEADING_CHAR_TAIL_DIM_FACTOR_END: 0.25,
  LIGHT_THEME_COLORS: {
    REGULAR_CHAR_COLOR_SOURCE:
      "var(--matrix-effect-light-regular-color, #3a7ca5)",
    REGULAR_CHAR_ALPHA: 0.7,
    LEADING_CHAR_COLOR_SOURCE:
      "var(--matrix-effect-light-leading-color, #16425b)",
    LEADING_CHAR_ALPHA: 0.9,
  },
  DARK_THEME_COLORS: {
    REGULAR_CHAR_COLOR_SOURCE:
      "var(--matrix-effect-dark-regular-color, #2a9d8f)",
    REGULAR_CHAR_ALPHA: 0.7,
    LEADING_CHAR_COLOR_SOURCE:
      "var(--matrix-effect-dark-leading-color, #e9c46a)",
    LEADING_CHAR_ALPHA: 0.88,
  },
  EFFECTIVE_REGULAR_CHAR_RGBA: "rgba(0,0,0,0)",
  EFFECTIVE_LEADING_CHAR_RGBA: "rgba(0,0,0,0)",
  MOUSE_INTERACTION_RADIUS: 60,
  MOUSE_PUSH_STRENGTH_FACTOR: 0.35,
  MOUSE_SPEED_INCREASE_FACTOR: 1.8,
  MOUSE_INTERACTION_MAX_Z_DEPTH: -45,
  MOUSE_RIPPLE_STRENGTH_FACTOR: 0.12,
  MOUSE_RIPPLE_FREQUENCY_FACTOR: 8.5,
  INTERACTION_LERP_SPEED: 0.07,
  MOUSE_RIPPLE_LERP_SPEED: 0.09,
  MOUSE_INTERACTION_SCALE_FACTOR: 1.04,
  BASE_Y_VELOCITY_MIN_FACTOR: 0.5,
  BASE_Y_VELOCITY_MAX_FACTOR: 0.6,
  Y_VELOCITY_DELTA_MULTIPLIER: 50,
  MIN_SPAWN_INTERVAL_MS: 1200,
  MAX_SPAWN_INTERVAL_MS: 2200,
  HORIZONTAL_DRIFT_SPEED_FACTOR: 0.025,
  HORIZONTAL_DRIFT_AMPLITUDE_MIN_FACTOR: 0.015,
  HORIZONTAL_DRIFT_AMPLITUDE_MAX_FACTOR: 0.12,
  HORIZONTAL_DRIFT_Y_POS_FACTOR: 0.002,
  SPRITE_FADE_IN_DISTANCE_CHARS: 2.5,
  SPRITE_FADE_OUT_DISTANCE_CHARS: 7.0,
  MIN_TARGET_OPACITY_REGULAR: 0.3,
  MAX_TARGET_OPACITY_REGULAR: 0.5,
  TARGET_OPACITY_LEADING: 0.75,
  OPACITY_LERP_SPEED: 0.1,
  NON_LEADING_CHAR_CHANGE_CHANCE: 0.004,
  LEADING_CHAR_CHANGE_CHANCE: 0.08,
  RENDERER_PIXEL_RATIO_CAP: 1.5,
  RENDERER_ANTIALIAS: true,
  STREAM_MIN_DEPTH_FACTOR: 0.65,
  STREAM_MAX_DEPTH_FACTOR: 1.0,
  CAMERA_FOV: 50,
  CAMERA_NEAR_PLANE: 6,
  CAMERA_FAR_PLANE: 1000,
  CAMERA_INITIAL_Z_POS: 90,
  MIN_STREAM_Z_DEPTH: -340,
  MAX_STREAM_Z_DEPTH: -35,
  SPAWN_VOLUME_Y_HALF_HEIGHT: 120,
  SPAWN_VOLUME_X_SPREAD_FACTOR: 2,
};

export const lowQualityConfig: MatrixRainConfig = {
  ...baseConfig,
  PREFILL_DURATION_SECONDS: 0.5,
  FONT_SIZE_PX: 8,
  TEXTURE_RESOLUTION_MULTIPLIER: 1.0,
  MIN_SPRITE_SCALE: 0.9,
  MAX_SPRITE_SCALE: 1.0,
  LEADING_CHAR_GLOW_OPACITY: 0,
  LEADING_CHAR_GLOW_BLUR: 0,
  LIGHT_THEME_COLORS: {
    REGULAR_CHAR_COLOR_SOURCE:
      "var(--matrix-effect-light-regular-color, #3a7ca5)",
    REGULAR_CHAR_ALPHA: 0.45,
    LEADING_CHAR_COLOR_SOURCE:
      "var(--matrix-effect-light-leading-color, #16425b)",
    LEADING_CHAR_ALPHA: 0.65,
  },
  DARK_THEME_COLORS: {
    REGULAR_CHAR_COLOR_SOURCE:
      "var(--matrix-effect-dark-regular-color, #2a9d8f)",
    REGULAR_CHAR_ALPHA: 0.35,
    LEADING_CHAR_COLOR_SOURCE:
      "var(--matrix-effect-dark-leading-color, #e9c46a)",
    LEADING_CHAR_ALPHA: 0.65,
  },
  MOUSE_INTERACTION_RADIUS: 40,
  MOUSE_RIPPLE_STRENGTH_FACTOR: 0.05,
  MOUSE_INTERACTION_SCALE_FACTOR: 1.0,
  BASE_Y_VELOCITY_MIN_FACTOR: 0.3,
  BASE_Y_VELOCITY_MAX_FACTOR: 0.7,
  MIN_SPAWN_INTERVAL_MS: 1500,
  MAX_SPAWN_INTERVAL_MS: 3000,
  COLUMN_BASE_WIDTH_PX_FACTOR: 1.0,
  SPAWN_VOLUME_X_SPREAD_FACTOR: 1.5,
  RENDERER_PIXEL_RATIO_CAP: 1.0,
  RENDERER_ANTIALIAS: false,
  STREAM_MIN_DEPTH_FACTOR: 0.5,
  CAMERA_FOV: 60,
  MIN_STREAM_Z_DEPTH: -250,
  MAX_STREAM_Z_DEPTH: -30,
};

export const mediumQualityConfig: MatrixRainConfig = {
  ...baseConfig,
};

export const ultraQualityConfig: MatrixRainConfig = {
  ...baseConfig,
  PREFILL_DURATION_SECONDS: 3.0,
  FONT_SIZE_PX: 13,
  TEXTURE_RESOLUTION_MULTIPLIER: 2.2,
  MIN_SPRITE_SCALE: 0.6,
  MAX_SPRITE_SCALE: 1.3,
  LEADING_CHAR_GLOW_OPACITY: 0.35,
  LEADING_CHAR_GLOW_BLUR: 1.8,
  LIGHT_THEME_COLORS: {
    REGULAR_CHAR_COLOR_SOURCE:
      "var(--matrix-effect-light-regular-ultra-color, #3a7ca5)",
    REGULAR_CHAR_ALPHA: 0.75,
    LEADING_CHAR_COLOR_SOURCE:
      "var(--matrix-effect-light-leading-ultra-color, #16425b)",
    LEADING_CHAR_ALPHA: 0.95,
  },
  DARK_THEME_COLORS: {
    REGULAR_CHAR_COLOR_SOURCE:
      "var(--matrix-effect-dark-regular-ultra-color, #2a9d8f)",
    REGULAR_CHAR_ALPHA: 0.75,
    LEADING_CHAR_COLOR_SOURCE:
      "var(--matrix-effect-dark-leading-ultra-color, #e9c46a)",
    LEADING_CHAR_ALPHA: 0.95,
  },
  MOUSE_INTERACTION_RADIUS: 90,
  MOUSE_PUSH_STRENGTH_FACTOR: 1.2,
  MOUSE_SPEED_INCREASE_FACTOR: 1.2,
  MOUSE_RIPPLE_STRENGTH_FACTOR: 0.2,
  MOUSE_RIPPLE_FREQUENCY_FACTOR: 10,
  INTERACTION_LERP_SPEED: 0.1,
  MOUSE_RIPPLE_LERP_SPEED: 0.1,
  MOUSE_INTERACTION_SCALE_FACTOR: 1.1,
  BASE_Y_VELOCITY_MIN_FACTOR: 0.3,
  BASE_Y_VELOCITY_MAX_FACTOR: 0.8,
  MIN_SPAWN_INTERVAL_MS: 80,
  MAX_SPAWN_INTERVAL_MS: 600,
  COLUMN_BASE_WIDTH_PX_FACTOR: 0.65,
  SPAWN_VOLUME_X_SPREAD_FACTOR: 3.8,
  RENDERER_PIXEL_RATIO_CAP: 2.0,
  RENDERER_ANTIALIAS: true,
  STREAM_MIN_DEPTH_FACTOR: 0.25,
  CAMERA_FOV: 55,
  CAMERA_INITIAL_Z_POS: 80,
  MIN_STREAM_Z_DEPTH: -500,
  MAX_STREAM_Z_DEPTH: -15,
};

export const defaultConfig: MatrixRainConfig = mediumQualityConfig;
